### PR TITLE
Minor admin stuff

### PR DESCRIPTION
**Pull request by samoht**
Don't merge yet, I'll add the travis scripts as well

### CODE REVIEW

**Comment by Drup** [comment]
You need to pin fmt too.

**Comment by samoht** [comment]
Hum this doesn't compile with 4.01. Not sure we are ready to drop 4.01 support yet.

**Comment by Drup** [comment]
probably some "module M = M'" in some .mli, let me see.

**Comment by samoht** [comment]
yes this is indeed due to the module aliases. I'm wondering if it makes sense to have only one public .mli instead of spread the documentation over 3 and use aliases.

(the opam file also miss some availability constraint)

**Comment by Drup** [comment]
4, not 7, the others are internal. And I do prefer to have the interface associated with its module instead of bundled together in one big .mli that is a pain to edit as it goes bigger and more messy. The documentation will have hyperlinks anyway, so I don't see the issue.

**Comment by samoht** [comment]
I have no strong opinion on this, although it is usually easier to read and better organised (for the library user) when everything is in one place.

**Comment by Drup** [comment]
Can you rebase and put the appropriate constraints ?

**Comment by Drup** [comment]
Also, to solve #16, I would really like to automatically download and build mirage-skeleton.

**Comment by samoht** [comment]
I've rebased. It's a bit hard currently to clone and test mirage-skeleton because it needs a new release of mirage. I'll add some runes anyway that could be cleaned-up later.

**Comment by Drup** [comment]
I missed a bit for compat. It's fixed. you can rebase.

**Comment by samoht** [comment]
rebased

**Comment by Drup** [comment]
It's green \o/

Can't we use REVDEPS instead of the manual opam launch ?

**Comment by samoht** [comment]
Good points for REVDEPS, updated.

**Comment by Drup** [comment]
Hum, I realized this actually doesn't build mirage-skeleton. The opam package apparently does nothing. why is that ?

**Comment by samoht** [comment]
Hum... I think that's because you cannot call Opam inside Opam. Need to double check.

**Comment by samoht** [comment]
All green! (for real this time)

**Comment by Drup** [comment]
Yay! And it's testing xen too, which is really useful. Thanks!

**Pull request merged**
