### PR TITLE
Fix some issues raised in @Drup's review of #46.

### PR DESCRIPTION
**Pull request by yallop**
https://github.com/mirage/functoria/pull/46#issuecomment-165178237

### CODE REVIEW

**Comment by Drup** [comment]
There is also the matching of peek in functoria_app, [here](https://github.com/mirage/functoria/blob/a6de812f552c55ad6f5842e561932521a8a27ede/app/functoria_app.ml#L641-L646).

**Comment by yallop** [comment]
That one seems a bit different: it needs the first component of the pair returned by `eval_peek_opts`, whereas the other cases need the second component.

**Comment by Drup** [comment]
I'm pretty sure I wondered why at some point, found the answer, and forgot it again. Which mean we should add a comment. :)

**Comment by yallop** [comment]
I've changed my mind: I don't think there's a difference in behaviour compared to the usual style here, so I've changed the code instead (cdb9ff7).

**Comment by Drup** [comment]
Ok. Holidays have ended, merging!

**Pull request merged**
