### PR TITLE
Add a build-test field to the opam file.

### PR DESCRIPTION
**Pull request by yallop**
Perhaps this'll cause the tests to run during Travis builds.

### CODE REVIEW

**Comment by Drup** [comment]
You should use opam filters. `onuit {test]` in depends and `--enable-tests {test}` in the configure.

**Comment by yallop** [comment]
Hmm.  I already have the `{test}` filter in `depends`, and pass `--enable-tests` if `ounit` is available, which seems to be [sufficient](https://travis-ci.org/mirage/functoria/jobs/97225540#L1146) to cause the tests to run on Travis.

**Comment by Drup** [comment]
Ah, that's the line I was looking for, and I missed it. Perfect then.

**Comment by Drup** [comment]
The CI failed and I don't understand why: https://travis-ci.org/mirage/functoria/jobs/97356688#L2622. Any idea ?

**Pull request merged**
