### PR TITLE
Restore compat with 4.01

### PR DESCRIPTION
**Pull request by Drup**
Minimal changes to make it work. those `module type of struct include` annoys me to no end.

### CODE REVIEW

**Comment by samoht** [comment]
why not simply `module type of X`?

**Comment by avsm** [comment]
I think this is a reasonable time to go 4.02-only for Mirage..

**Comment by mor1** [comment]
@avsm Out of interest, does anyone try to maintain stats on use (or
perhaps, "reach") of the different OCaml compiler versions?

On 17 September 2015 at 17:00, Anil Madhavapeddy <notifications@github.com>
wrote:

> I think this is a reasonable time to go 4.02-only for Mirage..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/functoria/pull/19#issuecomment-141132515>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by samoht** [comment]
I think we should keep compat as long as it not too much a pain. In that case, the changes are minimal, although not very pretty so that's fine.

Also, I think it's good to keep supporting the last 2 major versions of OCaml, to let people evolve their code-base.

**Comment by avsm** [comment]
Not to my knowledge. The only source of this is the OPAM compiler-version constraints.

**Comment by mor1** [comment]
Ack. I guess that analysis would be a start, to see how fast package
maintainers are switching.
Not even download stats from places where compiler is installed from?

On 17 September 2015 at 17:10, Anil Madhavapeddy <notifications@github.com>
wrote:

> Not to my knowledge. The only source of this is the OPAM compiler-version
> constraints.
>
> > On 17 Sep 2015, at 17:08, Richard Mortier <notifications@github.com>
> wrote:
> >
> > @avsm Out of interest, does anyone try to maintain stats on use (or
> > perhaps, "reach") of the different OCaml compiler versions?
> >
> > On 17 September 2015 at 17:00, Anil Madhavapeddy <
> notifications@github.com>
> > wrote:
> >
> > > I think this is a reasonable time to go 4.02-only for Mirage..
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/mirage/functoria/pull/19#issuecomment-141132515>.
> > >
> >
> >
> >
> > --
> > Richard Mortier
> > mort@cantab.net
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/mirage/functoria/pull/19#issuecomment-141134844>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/functoria/pull/19#issuecomment-141135201>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by avsm** [comment]
Fine by me.

**Comment by dbuenzli** [comment]
Le jeudi, 17 septembre 2015 à 17:17, Richard Mortier a écrit :
> Not even download stats from places where compiler is installed from?

I don't think we give a damn about download stats, it's a flawed metric anyways. What Thomas proposes is the right way of proceeding. I.e. say you support at least X version before the latest release. Given that OCaml major releases are semi-predictable it gives you, from a software maintenance perspective, a timeframe to plan your migration and whip programmers.

(This however doesn't the consider the question of package managers lingering with old ocaml versions which you may want to put in the equation, depends a bit on the kind of apps you develop)

Best,

Daniel

**Comment by mor1** [comment]
Flawed metric? Depends what's being inferred.

If there was some way to track the rate of installation of new compiler releases, as eg Google do with Android versions, then you might get some idea of the rate of uptake of a new release and what proportion of the community you're losing by forcing an upgrade.

Ditto looking at OPAM package repo and seeing how many (or better, rate at which) packages are mandating moving to newer releases.

**Comment by Drup** [comment]
@samoht 

if you do `module M = module type of include X end` then for all type `t` in `X`, `M.t = X.t`. This is not the case without the `include`. 

Yes, that's a feature of the OCaml module system...

**Comment by dbuenzli** [comment]
Le jeudi, 17 septembre 2015 à 17:48, Richard Mortier a écrit :
> Flawed metric? Depends what's being inferred.

The data itself is flawed. Garbage in, garbage out.

> Ditto looking at OPAM package repo and seeing how many (or better, rate at which) packages are mandating moving to newer releases.
That only tells you something about package developers (which are more keen on using the latest shiny features), not package *users*. If it were only me I would rewrite cmdliner using gadts, but I have a very important user that needs 3.12.0.

Using these numbers completely misses the point of being able to derive timeframes for maintenance which is what you want from a user point of view. You don't want support to be kept or dropped based on whathever broken metric one can invent.

Best,

Daniel

**Pull request merged**
