### PR TITLE
Topkg

### PR DESCRIPTION
**Pull request by samoht**
@Drup I've removed `lib/functoria_sigs.mli` as it seems that nobody was using it. Do you remember what it was for?

@yallop I've got some errors running the tests:
```
==============================================================================
Error: Command-line parsing tests:5:describe.

File "/Users/thomas/git/functoria/_build/oUnit-Command-line parsing tests-roccapina.local#02.log", line 8, characters 1-1:
Error: Command-line parsing tests:5:describe (in the log).

Raised at file "src/oUnitAssert.ml", line 45, characters 8-27
Called from file "src/oUnitRunner.ml", line 46, characters 13-26

not equal
------------------------------------------------------------------------------
==============================================================================
Error: Command-line parsing tests:2:read_config_file.

File "/Users/thomas/git/functoria/_build/oUnit-Command-line parsing tests-roccapina.local#01.log", line 5, characters 1-1:
Error: Command-line parsing tests:2:read_config_file (in the log).

File "tests/test_functoria_command_line.ml", line 195, characters 1-1:
Error: Command-line parsing tests:2:read_config_file (in the code).

not equal
------------------------------------------------------------------------------
```
Do you have an idea of what it means? :-)

### CODE REVIEW

**Comment by yallop** [comment]
I think this might need a version constraint for `topkg`.

**Comment by samoht** [comment]
@yallop I've added a constraint for the `--pinned` command-line argument support. Did you have something else in mind?

**Comment by yallop** [comment]
Thanks; that's fine.  I initially tried to build with `topkg` 0.7.1 and saw mysterious failures.  But I've upgraded to 0.7.6 and the build is working now.

**Comment by yallop** [comment]
However, `make test` doesn't do anything:

```
$ make test
ocaml pkg/pkg.ml test
pkg.ml: No tests to run.
```

**Comment by samoht** [comment]
@yallop ha yes, you need to remove the `run:false` in `pkg/pkg.ml`

**Comment by yallop** [comment]
@samoht: the tests are failing because there's no `config.ml` file:

```
$ make test
[... failure ...]
$ touch config.ml
$ make test
[ ... success ... ]
```

**Comment by samoht** [comment]
ha the tests have to run in `tests/`. Good catch!

**Pull request merged**
