### PR TITLE
Add a --output option to configure

### PR DESCRIPTION
**Pull request by samoht**
That option is used to overwrite the name of the unikernel, eg. this
enables the workflow:

```
mirage configre -o foo
make
./foo
```

### CODE REVIEW

**Comment by samoht** [comment]
I am not sure the implementation is the more efficient one,  I've tried to update the info type instead, but I didn't managed to make something cleaner.

/cc @Drup and @yallop

**Comment by yomimono** [comment]
This change looks larger than I'd expect for the feature (which itself is a good idea, IMO).  I'd really appreciate some attention from @drup or @yallop on this PR.

**Comment by hannesm** [comment]
Hmm, out of the blue I'd add the `-o` only for configure, which is then in the cache, and reused for build, depend, and clean!?!

**Comment by samoht** [comment]
I have simplified my patch as suggested by @hannesm

**Comment by hannesm** [comment]
LGTM, thx.  when travis is happy, I think this is good to merge.

**Comment by Drup** [comment]
I gave a very quick look, it looks ok. The additions are a bit sprinkled everywhere, but that's not exactly surprising.

**Comment by djs55** [comment]
Travis is happy, I think we can merge!

**Pull request merged**
