### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by Drup**
Goes with https://github.com/mirage/mirage/pull/454

### CODE REVIEW

**Comment by samoht** [comment]
> The fact that @dbuenzli didn't use labels at the time shouldn't force us to make the same mistakes.

I don't comment on how good or bad is the design. I just don't want users to learn 2 APIs just for the sake of it. Also, there are already quite a bit of existing examples using Cmdliner's API, so that makes it (relatively) easy to copy/paste to Functoria.

If I had to comment on the design issue, I'd say than I'm also not sure what labels bring here, appart unnecessary verbosity...

**Comment by avsm** [comment]
+1 to this comment. Could we make labels a future revision rev, and just let the more familiar API settle in first?

**Comment by Drup** [comment]
The contentious commit has been removed.

**Comment by samoht** [comment]
Thanks!

There's an issue with `Bootvar_gen`:

```
+ ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package sexplib -package mirage.runtime -package mirage-types.lwt -package mirage-console.xen -package mirage-bootvar -package lwt.syntax -package functoria.runtime -syntax camlp4o -o unikernel.cmo unikernel.ml
File "unikernel.ml", line 7, characters 15-32:
Error: Unbound module Bootvar_gen
Command exited with code 2.
Compilation unsuccessful after building 5 targets (0 cached) in 00:00:00.
make[1]: *** [main.native.o] Error 10
make[1]: Leaving directory `/home/travis/build/mirage/functoria/mirage-skeleton.dev/hello'
make: *** [hello-build] Error 2
```

**Comment by Drup** [comment]
Ah, yes! I forgot to push the fix on mirage-skeleton.

**Comment by Drup** [comment]
All green now.

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
